//
// Created by mehdi on 05/02/16.
//

#ifndef IMAC3_MOTEURSPHYSIQUES_PARTYKEL_CONSTANTFORCE2D_HPP
#define IMAC3_MOTEURSPHYSIQUES_PARTYKEL_CONSTANTFORCE2D_HPP

class ConstantForce2D
{

};

#endif //IMAC3_MOTEURSPHYSIQUES_PARTYKEL_CONSTANTFORCE2D_HPP
