//
// Created by mehdi on 05/02/16.
//

#ifndef IMAC3_MOTEURSPHYSIQUES_PARTYKEL_PARTICLEMANAGER2D_HPP
#define IMAC3_MOTEURSPHYSIQUES_PARTYKEL_PARTICLEMANAGER2D_HPP

class ParticleManager2D
{

};

#endif //IMAC3_MOTEURSPHYSIQUES_PARTYKEL_PARTICLEMANAGER2D_HPP
