//
// Created by mehdi on 05/02/16.
//

#ifndef IMAC3_MOTEURSPHYSIQUES_PARTYKEL_POLYGON2D_HPP
#define IMAC3_MOTEURSPHYSIQUES_PARTYKEL_POLYGON2D_HPP

class Polygon2D
{

};

#endif //IMAC3_MOTEURSPHYSIQUES_PARTYKEL_POLYGON2D_HPP
